# Web Scraping and Data Cleaning

This notebook utilizes the library BeautifulSoup to scrape statistics from pro-football-reference.com for the Top 24 ranked rookie running backs and then uses the library Pandas to place the statistics in a dataframe and clean the data.

In [ ]:
import requests
from bs4 import BeautifulSoup as soup

In [181]:
urls = ['https://www.pro-football-reference.com/players/J/JacoJo01.htm',
       'https://www.pro-football-reference.com/players/S/SandMi01.htm',
       'https://www.pro-football-reference.com/players/S/SingDe00.htm',
       'https://www.pro-football-reference.com/players/M/MontDa01.htm',
       'https://www.pro-football-reference.com/players/M/MattAl01.htm',
       'https://www.pro-football-reference.com/players/S/SnelBe00.htm',
       'https://www.pro-football-reference.com/players/H/HillJo03.htm',
       'https://www.pro-football-reference.com/players/P/PollTo00.htm',
       'https://www.pro-football-reference.com/players/H/HillWe00.htm',
       'https://www.pro-football-reference.com/players/W/WhytKe00.htm',
       'https://www.pro-football-reference.com/players/H/HendDa00.htm',
       'https://www.pro-football-reference.com/players/G/GaskMy00.htm',
       'https://www.pro-football-reference.com/players/J/JohnTy02.htm',
       'https://www.pro-football-reference.com/players/H/HillJu00.htm',
       'https://www.pro-football-reference.com/players/L/LairPa00.htm',
       'https://www.pro-football-reference.com/players/T/ThomDa06.htm',
       'https://www.pro-football-reference.com/players/H/HomeTr00.htm',
       'https://www.pro-football-reference.com/players/A/ArmsRy00.htm',
       'https://www.pro-football-reference.com/players/O/OlliQa00.htm',
       'https://www.pro-football-reference.com/players/H/HarrDa06.htm',
       'https://www.pro-football-reference.com/players/W/WillDe07.htm',
       'https://www.pro-football-reference.com/players/O/OzigDe01.htm',
       'https://www.pro-football-reference.com/players/I/IngoAl01.htm',
       'https://www.pro-football-reference.com/players/S/ScarJo00.htm']

In [182]:
def stats_retrieve(url):
    r = requests.get(url)
    c = r.content

    page = soup(c, 'html.parser')
    #finding the 2019 rushing and receiving stats table
    table = page.find("tr",{"id":"rushing_and_receiving.2019"})

    #taking the stats elements from the table
    stats = table.findAll("td")

    #runs through the statistics row and puts each item into a list    
    stat_table = [stat.text for stat in stats]

    #takes the player name and trims an empty space found
    player_name = page.find("h1",{"itemprop":"name"}).text.strip()
    stats_table = [player_name] + stat_table
    return stats_table

In [184]:
#takes top 24 Rookie Running Back statistics from Pro Football Reference
rookie_stats = [stats_retrieve(url) for url in urls]
print(rookie_stats)

[['Josh Jacobs', '21', 'OAK', 'RB', '28', '13', '13', '242', '1150', '7', '53', '51', '4.8', '88.5', '18.6', '27', '20', '166', '8.3', '0', '8', '28', '1.5', '12.8', '74.1%', '6.1', '262', '5.0', '1316', '7', '1', '8'], ['Miles Sanders', '22', 'PHI', 'RB', '26', '16', '11', '179', '818', '3', '33', '65', '4.6', '51.1', '11.2', '63', '50', '509', '10.2', '3', '19', '45', '3.1', '31.8', '79.4%', '8.1', '229', '5.8', '1327', '6', '2', '9'], ['Devin Singletary', '22', 'BUF', 'RB', '26', '12', '8', '151', '775', '2', '39', '38', '5.1', '64.6', '12.6', '41', '29', '194', '6.7', '2', '9', '49', '2.4', '16.2', '70.7%', '4.7', '180', '5.4', '969', '4', '4', '6'], ['David Montgomery', '22', 'CHI', 'RB', '32', '16', '8', '242', '889', '6', '50', '55', '3.7', '55.6', '15.1', '35', '25', '185', '7.4', '1', '7', '30', '1.6', '11.6', '71.4%', '5.3', '267', '4.0', '1074', '7', '2', '5'], ['Alexander Mattison', '21', 'MIN', '', '25', '13', '0', '100', '462', '1', '20', '35', '4.6', '35.5', '7.7', '12', '10', '82', '8.2', '0', '3', '17', '0.8', '6.3', '83.3%', '6.8', '110', '4.9', '544', '1', '1', '4'], ['Benny Snell Jr.', '21', 'PIT', 'rb', '24', '13', '2', '108', '426', '2', '19', '23', '3.9', '32.8', '8.3', '4', '3', '23', '7.7', '0', '0', '14', '0.2', '1.8', '75.0%', '5.8', '111', '4.0', '449', '2', '1', '3'], ['Jon Hilliman', '24', 'NYG', 'rb', '23', '3', '1', '30', '91', '0', '6', '10', '3.0', '30.3', '10.0', '4', '3', '1', '0.3', '0', '0', '5', '1.0', '0.3', '75.0%', '0.3', '33', '2.8', '92', '0', '2', '1'], ['Tony Pollard', '22', 'DAL', '', '20', '15', '0', '86', '455', '2', '21', '44', '5.3', '30.3', '5.7', '20', '15', '107', '7.1', '1', '4', '21', '1.0', '7.1', '75.0%', '5.4', '101', '5.6', '562', '3', '1', '4'], ['Wes Hills', '24', 'DET', 'rb', '36', '1', '1', '10', '21', '2', '3', '15', '2.1', '21.0', '10.0', '2', '2', '1', '0.5', '0', '0', '2', '2.0', '1.0', '100.0%', '0.5', '12', '1.8', '22', '2', '0', '0'], ['Kerrith Whyte Jr', '23', 'PIT', '', '38', '6', '0', '24', '122', '0', '5', '21', '5.1', '20.3', '4.0', '1', '1', '9', '9.0', '0', '1', '9', '0.2', '1.5', '100.0%', '9.0', '25', '5.2', '131', '0', '0', '1'], ['Darrell Henderson', '22', 'LAR', '', '27', '13', '0', '39', '147', '0', '10', '22', '3.8', '11.3', '3.0', '6', '4', '37', '9.3', '0', '1', '14', '0.3', '2.8', '66.7%', '6.2', '43', '4.3', '184', '0', '0', '1'], ['Myles Gaskin', '22', 'MIA', '', '37', '7', '0', '36', '133', '1', '7', '27', '3.7', '19.0', '5.1', '12', '7', '51', '7.3', '0', '2', '20', '1.0', '7.3', '58.3%', '4.3', '43', '4.3', '184', '1', '0', '1'], ['Ty Johnson', '22', 'DET', 'rb', '31', '16', '1', '63', '273', '0', '11', '40', '4.3', '17.1', '3.9', '31', '24', '109', '4.5', '0', '4', '13', '1.5', '6.8', '77.4%', '3.5', '87', '4.4', '382', '0', '1', '2'], ['Justice Hill', '22', 'BAL', '', '43', '16', '0', '58', '225', '2', '10', '18', '3.9', '14.1', '3.6', '15', '8', '70', '8.8', '0', '5', '14', '0.5', '4.4', '53.3%', '4.7', '66', '4.5', '295', '2', '0', '3'], ['Patrick Laird', '24', 'MIA', 'rb', '42', '15', '4', '62', '168', '1', '9', '18', '2.7', '11.2', '4.1', '30', '23', '204', '8.9', '0', '13', '21', '1.5', '13.6', '76.7%', '6.8', '85', '4.4', '372', '1', '0', '3'], ['Darwin Thompson', '23', 'KAN', '', '34', '12', '0', '37', '128', '1', '9', '12', '3.5', '10.7', '3.1', '10', '9', '43', '4.8', '0', '2', '19', '0.8', '3.6', '90.0%', '4.3', '46', '3.7', '171', '1', '0', '1'], ['Travis Homer', '21', 'SEA', 'rb', '25', '16', '1', '18', '114', '0', '7', '29', '6.3', '7.1', '1.1', '13', '11', '56', '5.1', '0', '3', '11', '0.7', '3.5', '84.6%', '4.3', '29', '5.9', '170', '0', '0', '1'], ['Ryquell Armstead', '23', 'JAX', 'rb', '23', '16', '1', '35', '108', '0', '5', '16', '3.1', '6.8', '2.2', '24', '14', '144', '10.3', '2', '9', '31', '0.9', '9.0', '58.3%', '6.0', '49', '5.1', '252', '2', '0', '2'], ['Qadree Ollison', '23', 'ATL', '', '30', '8', '0', '22', '50', '4', '6', '6', '2.3', '6.3', '2.8', '2', '1', '7', '7.0', '0', '1', '7', '0.1', '0.9', '50.0%', '3.5', '23', '2.5', '57', '4', '1', '0'], ['Damien Harris', '22', 'NWE', '', '37', '2', '0', '4', '12', '0', '', '13', '3.0', '6.0', '2.0', '', '', '', '', '', '', '', '', '', '', '', '4', '3.0', '12', '0', '0', '0'], ['Dexter Williams', '22', 'GNB', '', '22', '4', '0', '5', '11', '0', '', '5', '2.2', '2.8', '1.3', '', '', '', '', '', '', '', '', '', '', '', '5', '2.2', '11', '0', '0', '0'], ['Devine Ozigbo', '23', 'JAX', '', '33', '10', '0', '9', '27', '0', '1', '9', '3.0', '2.7', '0.9', '5', '3', '23', '7.7', '0', '1', '12', '0.3', '2.3', '60.0%', '4.6', '12', '4.2', '50', '0', '0', '0'], ['Alec Ingold', '23', 'OAK', 'fb', '45', '16', '4', '10', '17', '0', '7', '4', '1.7', '1.1', '0.6', '6', '6', '44', '7.3', '1', '4', '14', '0.4', '2.8', '100.0%', '7.3', '16', '3.8', '61', '1', '0', '0'], ['Jordan Scarlett', '23', 'CAR', '', '20', '9', '0', '4', '9', '0', '', '6', '2.3', '1.0', '0.4', '', '', '', '', '', '', '', '', '', '', '', '4', '2.3', '9', '0', '0', '0']]

In [139]:
#lets find the column headers
table_headers = page.find("table",{"id":"rushing_and_receiving"})
headers = table_headers.find("tr").find_next("tr")
column_headers = [th.text for th in headers.findAll("th")]
print(column_headers)

['Year', 'Age', 'Tm', 'Pos', 'No.', 'G', 'GS', 'Rush', 'Yds', 'TD', '1D', 'Lng', 'Y/A', 'Y/G', 'A/G', 'Tgt', 'Rec', 'Yds', 'Y/R', 'TD', '1D', 'Lng', 'R/G', 'Y/G', 'Ctch%', 'Y/Tgt', 'Touch', 'Y/Tch', 'YScm', 'RRTD', 'Fmb', 'AV']

In [189]:
#changes first column name to match list of players
column_headers[0] = 'player_name'
print(column_headers)

['player_name', 'Age', 'Tm', 'Pos', 'No.', 'G', 'GS', 'Rush', 'Yds', 'TD', '1D', 'Lng', 'Y/A', 'Y/G', 'A/G', 'Tgt', 'Rec', 'Yds', 'Y/R', 'TD', '1D', 'Lng', 'R/G', 'Y/G', 'Ctch%', 'Y/Tgt', 'Touch', 'Y/Tch', 'YScm', 'RRTD', 'Fmb', 'AV']

In [412]:
import pandas as pd
df = pd.DataFrame(rookie_stats, columns=column_headers)
df.head(10)

,player_name,Age,Tm,Pos,No.,G,GS,Rush,Yds,TD,...,R/G,Y/G,Ctch%,Y/Tgt,Touch,Y/Tch,YScm,RRTD,Fmb,AV
0,Josh Jacobs,21,OAK,RB,28,13,13,242,1150,7,...,1.5,12.8,74.1%,6.1,262,5.0,1316,7,1,8
1,Miles Sanders,22,PHI,RB,26,16,11,179,818,3,...,3.1,31.8,79.4%,8.1,229,5.8,1327,6,2,9
2,Devin Singletary,22,BUF,RB,26,12,8,151,775,2,...,2.4,16.2,70.7%,4.7,180,5.4,969,4,4,6
3,David Montgomery,22,CHI,RB,32,16,8,242,889,6,...,1.6,11.6,71.4%,5.3,267,4.0,1074,7,2,5
4,Alexander Mattison,21,MIN,,25,13,0,100,462,1,...,0.8,6.3,83.3%,6.8,110,4.9,544,1,1,4
5,Benny Snell Jr.,21,PIT,rb,24,13,2,108,426,2,...,0.2,1.8,75.0%,5.8,111,4.0,449,2,1,3
6,Jon Hilliman,24,NYG,rb,23,3,1,30,91,0,...,1.0,0.3,75.0%,0.3,33,2.8,92,0,2,1
7,Tony Pollard,22,DAL,,20,15,0,86,455,2,...,1.0,7.1,75.0%,5.4,101,5.6,562,3,1,4
8,Wes Hills,24,DET,rb,36,1,1,10,21,2,...,2.0,1.0,100.0%,0.5,12,1.8,22,2,0,0
9,Kerrith Whyte Jr,23,PIT,,38,6,0,24,122,0,...,0.2,1.5,100.0%,9.0,25,5.2,131,0,0,1

In [413]:
#Now that stats are in a dataframe, drop some columns which are not super useful
print(df.columns)
df = df.drop(columns=['Age','Pos','No.','AV'])
df.head(2)

Index(['player_name', 'Age', 'Tm', 'Pos', 'No.', 'G', 'GS', 'Rush', 'Yds',
       'TD', '1D', 'Lng', 'Y/A', 'Y/G', 'A/G', 'Tgt', 'Rec', 'Yds', 'Y/R',
       'TD', '1D', 'Lng', 'R/G', 'Y/G', 'Ctch%', 'Y/Tgt', 'Touch', 'Y/Tch',
       'YScm', 'RRTD', 'Fmb', 'AV'],
      dtype='object')

,player_name,Tm,G,GS,Rush,Yds,TD,1D,Lng,Y/A,...,Lng,R/G,Y/G,Ctch%,Y/Tgt,Touch,Y/Tch,YScm,RRTD,Fmb
0,Josh Jacobs,OAK,13,13,242,1150,7,53,51,4.8,...,28,1.5,12.8,74.1%,6.1,262,5.0,1316,7,1
1,Miles Sanders,PHI,16,11,179,818,3,33,65,4.6,...,45,3.1,31.8,79.4%,8.1,229,5.8,1327,6,2

In [414]:
df = df.rename(str.lower, axis='columns')

In [415]:
#Changing column names that have identical names

#convert column names into single array
columns = pd.Series(df.columns)
for column in columns[columns.duplicated()]:
    #for every column name which is in the duplicated column names list, concatenate an .string(integer)
    columns[columns[columns == column].index.values.tolist()] = [column + '.' + str(i) if i != 0 else column for i in range(sum(columns == column))]

print(columns)
df.columns = columns

0     player_name
1              tm
2               g
3              gs
4            rush
5             yds
6              td
7              1d
8             lng
9             y/a
10            y/g
11            a/g
12            tgt
13            rec
14          yds.1
15            y/r
16           td.1
17           1d.1
18          lng.1
19            r/g
20          y/g.1
21          ctch%
22          y/tgt
23          touch
24          y/tch
25           yscm
26           rrtd
27            fmb
dtype: object

In [416]:
#a dictionary to rename the columns
df = df.rename(columns={'tm':'team',
           'g':'games_played',
           'gs':'games_started',
           'rush':'rush_attempts',
           'yds':'total_rush_yards',
           'td':'rush_td',
           '1d':'rush_first_downs',
           'lng':'longest_rush',
           'y/a':'rush_yards_per_attempt',
           'y/g':'rush_yards_per_game',
           'a/g':'attempts_per_game',
           'tgt':'pass_targets',
           'rec':'receptions',
           'yds.1':'total_receiving_yards',
           'y/r':'yards_per_reception',
           'td.1':'receiving_touchdowns',
           '1d.1':'receiving_first_downs',
           'lng.1':'longest_reception',
           'r/g':'receptions_per_game',
           'y/g.1':'receving_yards_per_game',
           'ctch%':'catch_percentage',
           'y/tgt':'receiving_yards_per_target',
           'touch':'total_touches',
           'y/tch':'yards_per_touch',
           'yscm':'scrimmage_yards',
           'rrtd':'total_touchdowns',
           'fmb':'fumbles'}
         )

In [417]:
#removes the percentage character from columns values
df['catch_percentage'] = df['catch_percentage'].replace('\%','',regex=True)

In [418]:
#converts all numeric columns to numeric datatypes, ignores error in the case of an object column
df = df.apply(pd.to_numeric,errors='ignore')
df.dtypes

player_name                    object
team                           object
games_played                    int64
games_started                   int64
rush_attempts                   int64
total_rush_yards                int64
rush_td                         int64
rush_first_downs              float64
longest_rush                    int64
rush_yards_per_attempt        float64
rush_yards_per_game           float64
attempts_per_game             float64
pass_targets                  float64
receptions                    float64
total_receiving_yards         float64
yards_per_reception           float64
receiving_touchdowns          float64
receiving_first_downs         float64
longest_reception             float64
receptions_per_game           float64
receving_yards_per_game       float64
catch_percentage              float64
receiving_yards_per_target    float64
total_touches                   int64
yards_per_touch               float64
scrimmage_yards                 int64
total_touchdowns                int64
fumbles                         int64
dtype: object

In [419]:
#Now that the data types are correct, handle missing values
df.isnull().sum()

player_name                   0
team                          0
games_played                  0
games_started                 0
rush_attempts                 0
total_rush_yards              0
rush_td                       0
rush_first_downs              3
longest_rush                  0
rush_yards_per_attempt        0
rush_yards_per_game           0
attempts_per_game             0
pass_targets                  3
receptions                    3
total_receiving_yards         3
yards_per_reception           3
receiving_touchdowns          3
receiving_first_downs         3
longest_reception             3
receptions_per_game           3
receving_yards_per_game       3
catch_percentage              3
receiving_yards_per_target    3
total_touches                 0
yards_per_touch               0
scrimmage_yards               0
total_touchdowns              0
fumbles                       0
dtype: int64

In [420]:
#take a look at the rows where there are null values
null_df = df[df.isnull().any(axis=1)]
null_df

,player_name,team,games_played,games_started,rush_attempts,total_rush_yards,rush_td,rush_first_downs,longest_rush,rush_yards_per_attempt,...,longest_reception,receptions_per_game,receving_yards_per_game,catch_percentage,receiving_yards_per_target,total_touches,yards_per_touch,scrimmage_yards,total_touchdowns,fumbles
19,Damien Harris,NWE,2,0,4,12,0,NaN,13,3.0,...,NaN,NaN,NaN,NaN,NaN,4,3.0,12,0,0
20,Dexter Williams,GNB,4,0,5,11,0,NaN,5,2.2,...,NaN,NaN,NaN,NaN,NaN,5,2.2,11,0,0
23,Jordan Scarlett,CAR,9,0,4,9,0,NaN,6,2.3,...,NaN,NaN,NaN,NaN,NaN,4,2.3,9,0,0

In [421]:
#replace null values with 0
df = df.fillna(value=0)
df.loc[[19,20,23]]

,player_name,team,games_played,games_started,rush_attempts,total_rush_yards,rush_td,rush_first_downs,longest_rush,rush_yards_per_attempt,...,longest_reception,receptions_per_game,receving_yards_per_game,catch_percentage,receiving_yards_per_target,total_touches,yards_per_touch,scrimmage_yards,total_touchdowns,fumbles
19,Damien Harris,NWE,2,0,4,12,0,0.0,13,3.0,...,0.0,0.0,0.0,0.0,0.0,4,3.0,12,0,0
20,Dexter Williams,GNB,4,0,5,11,0,0.0,5,2.2,...,0.0,0.0,0.0,0.0,0.0,5,2.2,11,0,0
23,Jordan Scarlett,CAR,9,0,4,9,0,0.0,6,2.3,...,0.0,0.0,0.0,0.0,0.0,4,2.3,9,0,0

In [425]:
#now to write the dataframe to a csv
df.to_csv('top_rookie_rb_2019.csv',index=False)